# baseURL = "http://mobyvb.com/lattice-hugo-demo"
baseURL = ""
languageCode = "en-us"
title = "Lattice"
theme = "lattice-theme"
publishDir = "docs"

sectionPagesMenu = "main"

[markup.goldmark.renderer]
  unsafe = true
